version: "3.9"

services:
  api:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@cano-db:5432/${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRATION_TIME: ${JWT_REFRESH_EXPIRATION_TIME}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      PORT: 3000
      NODE_ENV: production
      TZ: America/Bogota
      TYPEORM_SYNC: ${TYPEORM_SYNC}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.cano-api.rule=Host(`api-cano-distri.andresvps.cloud`)
      - traefik.http.routers.cano-api.entrypoints=websecure
      - traefik.http.routers.cano-api.tls.certresolver=letsencrypt
      - traefik.http.routers.cano-api-http.rule=Host(`api-cano-distri.andresvps.cloud`)
      - traefik.http.routers.cano-api-http.entrypoints=web
      - traefik.http.routers.cano-api-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.services.cano-api.loadbalancer.server.port=3000
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dokploy-network:
    external: true
